name: Build image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  ORGANIZATION: proyectos-enee
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: 'proyectos-enee/utcd/cobroprejuridico/backend'
  IMAGE_NAME_FRONTEND: 'proyectos-enee/utcd/cobroprejuridico/frontend'
  DB__CONEXION: 'Server=localhost;Database=enee;User Id=postgres; Password=P@ssword1234;Enlist=true;'

jobs:
  mobile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install pnpm
        working-directory: mobile
        run: npm install -g pnpm

      - name: Install dependencies
        working-directory: mobile
        run: |
          for i in 1 2 3; do
            pnpm install && break
            echo "pnpm install failed... retrying in 10s ($i/3)"
            sleep 10
          done

      - name: Install expo-dev-client
        working-directory: mobile
        run: npx expo install expo-dev-client

      - name: Install jq
        working-directory: mobile
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install EAS CLI
        working-directory: mobile
        run: npm install -g eas-cli

      - name: Build APK locally with EAS
        working-directory: mobile
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          eas build --platform android --profile preview --local --non-interactive --output=./app-release.apk

      - name: Rename APK with version tag
        working-directory: mobile
        id: rename_apk
        run: |
          VERSION=${{ github.ref_name }}
          NEW_NAME=UTCDForms-${VERSION}.apk
          mv app-release.apk $NEW_NAME
          echo "APK_FINAL_PATH=${NEW_NAME}" >> $GITHUB_OUTPUT

      - name: Check that APK file exists
        working-directory: mobile
        run: ls -lh ${{ steps.rename_apk.outputs.APK_FINAL_PATH }}

        # Upload APK to GitHub Release
      - name: Upload APK to existing GitHub Release using gh CLI
        working-directory: mobile
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF##*/}
          APK_FILE="UTCDForms-${VERSION}.apk"

          if [ -f "$APK_FILE" ]; then
            echo "Uploading $APK_FILE to release $VERSION..."
            gh release upload "$VERSION" "$APK_FILE" --clobber
          else
            echo "APK not found: $APK_FILE"
            exit 1
          fi
